#!/bin/bash

curl -X POST -H "Content-Type: application/json" -d '{"columns":[{"name":"A","type":"boolean"},{"name":"B","type":"int"},{"name":"C","type":"double"},{"name":"D","type":"string"}]}' http://localhost:5000/sheet/createSheet