#!/bin/bash

# create tow sheets
curl -X POST -H "Content-Type: application/json" -d '{"columns":[{"name":"A","type":"boolean"},{"name":"B","type":"int"},{"name":"C","type":"double"}]}' http://localhost:5000/sheet/createSheet
curl -X POST -H "Content-Type: application/json" -d '{"columns":[{"name":"A","type":"boolean"},{"name":"B","type":"int"},{"name":"C","type":"double"}]}' http://localhost:5000/sheet/createSheet

# add to sheet 1 3 rows
curl -X POST -H "Content-Type: application/json" -d '{"sheet_id":1, "column_name":"B", "row_number":1, "value":1}' http://localhost:5000/sheet/setCell
curl -X POST -H "Content-Type: application/json" -d '{"sheet_id":1, "column_name":"B", "row_number":2, "value":2}' http://localhost:5000/sheet/setCell
curl -X POST -H "Content-Type: application/json" -d '{"sheet_id":1, "column_name":"B", "row_number":3, "value":3}' http://localhost:5000/sheet/setCell

# look up 
curl -X POST -H "Content-Type: application/json" -d '{"sheet_id":1, "column_name":"B", "row_number":4, "value": "LOOKUP(B,1)"}' http://localhost:5000/sheet/setCell
